import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Link from 'next/link';
import Layout,{siteTitle} from "@/components/Layout";
import utileStyles from "../styles/utils.module.css";
import {getPostsData} from "../lib/post";



//SSGの場合
export async function getStaticProps() {
  
  
  const allPostsData = getPostsData();
  console.log(allPostsData);

  return {
    props: {
      allPostsData,
    }
  }
}



export default function Home({allPostsData}) {
  return (
    <>
      <Head>
        <title>{siteTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <Layout home>
        
        <section className={utileStyles.headingMd}>
          <p>私はフルスタックエンジニアです。Udemy講師として活動しています。好きな言語はtypescriptです</p>
        </section>

        <section>
          <h2 className={utileStyles.headingMd}>エンジニアのブログ</h2>
        </section>

        <div className={styles.grid}>
          {allPostsData.map(({id,title,date,thumbnail}) =>(
            <article key={id}>
            <Link href={`/posts/${id}`}>
              <img className={styles.thumbnailImage} src={thumbnail} alt="" />
            </Link>
            <Link className={utileStyles.boldText} href={`/posts/${id}`}>
              {title}
            </Link>
            <br />
            <small className={utileStyles.lightText}>
              {date}
            </small>
          </article>
          ))}
          

          
        </div>

        
    
      </Layout>
      
    </>
  );
}
